version: "3"

services:

  backend:
    build:
      context: ../
      dockerfile: ./Deploy/Dockerfile
    volumes:
      - './../Database:/var/lib/kefirchik'
    environment:
      - MODE=release
      - TG_TOKEN=secret
