version: "3"

services:

  backend:
    build:
      context: ../
      dockerfile: ./Deploy/Dockerfile
    volumes:
      - './../Database:/var/lib/kefirchik'
    ports:
     - "8443:8443"
    environment:
      - MODE=${MODE:-release}
      - TG_TOKEN=${TG_TOKEN}
